import {
  Stethoscope,
  Activity,
  Hand,
  Dumbbell,
  Brain,
  StretchHorizontal,
  Footprints,
  Sparkles,
  Scissors,
  Smile,
  Calculator,
  Scale,
  Briefcase,
  Home,
  HelpCircle,
  Car,
  Wrench,
  SprayCan,
  Zap,
  HardHat,
  Fan,
  Trees,
  PaintRoller,
  Utensils,
  Bed,
  CircleHelp,
  ClipboardPlus,
  Clock,
  TrendingUp,
  CalendarCheck,
  FilePlus2,
  UserCog,
  MessagesSquare,
  Wand2,
  LayoutGrid,
  Settings,
  ShieldCheck,
  Bell,
  RefreshCw,
  Trophy,
  Bot,
  UserCheck,
  Heart,
  Handshake,
} from "lucide-react";

const iconMap = {
  "user-check": UserCheck,
  heart: Heart,
  handshake: Handshake,
  "calendar-check": CalendarCheck,
  "file-plus": FilePlus2,
  "user-cog": UserCog,
  "messages-square": MessagesSquare,
  "wand": Wand2,
  "layout-grid": LayoutGrid,
  "settings": Settings,
  "shield-check": ShieldCheck,
  "clipboard-plus": ClipboardPlus,
  clock: Clock,
  "trending-up": TrendingUp,
  stethoscope: Stethoscope,
  activity: Activity,
  hand: Hand,
  dumbbell: Dumbbell,
  brain: Brain,
  "stretch-horizontal": StretchHorizontal,
  footprints: Footprints,
  sparkles: Sparkles,
  scissors: Scissors,
  smile: Smile,
  calculator: Calculator,
  scale: Scale,
  briefcase: Briefcase,
  home: Home,
  "help-circle": HelpCircle,
  car: Car,
  wrench: Wrench,
  "spray-can": SprayCan,
  zap: Zap,
  "hard-hat": HardHat,
  fan: Fan,
  trees: Trees,
  "paint-roller": PaintRoller,
  utensils: Utensils,
  bed: Bed,
  "circle-help": CircleHelp,
  bell: Bell,
  "refresh-cw": RefreshCw,
  trophy: Trophy,
  bot: Bot,
};

export default iconMap;